config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # catalog
  root to: "catalog#index"
  get "/catalog(/:category_slug)", to: "catalog#index", as: "catalog"
  resources :products, only: %i[show]
  resources :product_images, only: %i[destroy]

  # users
  resources :users, only: %i[new create update]
  resources :profile_images, only: %i[update destroy]
  resources :user_activations, only: %i[new edit]
  resources :password_resets, only: %i[new create edit update]
  get "/password_reset_success", to: "password_resets#mail_sent", as: "mail_sent"
  get "/profile", to: "profile#index", as: "profile"
  resources :sessions, only: %i[new create]
  resource :session, to: "sessions#destroy", only: %i[destroy], defaults: { id: nil }

  # carts and orders
  resource :cart, only: %i[show update]
  resources :orders, only: %i[new create]
  get "/orders/:uuid", to: "orders#show", as: "order_by_uuid"

  # admin pages
  namespace "admin" do
    get "/", to: "home#index"
    resources :products
    resources :product_categories
    resources :carts, only: %i[index show destroy]
    resources :orders, only: %i[index show destroy]
    resources :users, only: %i[index show edit update destroy] do
      resources :orders, only: %i[index]
    end
  end

  match "*unmatched", to: "application#render_404", via: :all
end

app/models/user.rb
class User < ApplicationRecord
  include ImageUrl

  attr_accessor :activation_token, :reset_token
  has_many :orders
  has_one :cart, dependent: :destroy
  has_secure_password
  has_one_attached :image

  validates :email, presence: true, uniqueness: true

  before_create :create_activation_digest

  def admin?
    is_admin
  end

  def activated?
    activated
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def update_activation_digest
    self.activation_token = Token.new_token
    update_attribute(:activation_digest, Token.digest(self.activation_token))
  end

  def create_reset_password_digest
    self.reset_token = Token.new_token
    update_attribute(:reset_password_digest,  Token.digest(reset_token))
    update_attribute(:reset_password_sent_at, Time.zone.now)
  end

  def password_reset_expired?
    reset_password_sent_at < 2.hours.ago
  end

  def send_activation_email
    UsersMailer.user_activation(self).deliver_now
  end

  def send_password_reset_email
    UsersMailer.password_reset(self).deliver_now
  end

  private

  def create_activation_digest
    self.activation_token = Token.new_token
    self.activation_digest = Token.digest(self.activation_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, except: [ :index ]

  def index
    @title = "Admin - Users"
    @users = User.all
  end

  def show
    @title = "Admin - User:#{params[:id]}"
  end

  def edit
    @title = "Admin - User:#{params[:id]}"
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User was successfully updated."
      redirect_to admin_user_path(@user)
    else
      flash.now[:warning] = "User wasn't updated!"
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User was successfully deleted."
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :is_admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      @user.send_activation_email
      flash[:success] = "Account was successfully created!"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/users/new.html.erb
<div class="container my-auto">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">Create a Brand new Account</h2>

      <%= form_for @user, url: users_path, method: :post do |form| %>
        <% if @user.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :email, class: "form-label" %>
          <%= form.email_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :password, class: "form-label" %>
          <%= form.password_field :password, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :password_confirmation, class: "form-label" %>
          <%= form.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="actions">
          <%= form.submit 'Create', class: "btn btn-primary" %>
        </div>
      <% end %>
      <div class="container text-center mt-3">
        Already have an account? <%= link_to "Sign In", new_session_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= @user.email %>, Hi, this is your profile page.
  <hr>
  <% @user.orders.each do |order| %>
    <%= render partial: "shared/order", locals: { order: order } %>
    <%# link_to "Order: #{order.id}", order_by_uuid_path(order.uuid), class: "btn btn-info mt-1" %>
  <% end %>
</div>