config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # catalog
  root to: "catalog#index"
  get "/catalog(/:category_slug)", to: "catalog#index", as: "catalog"
  resources :products, only: %i[show]
  resources :product_images, only: %i[destroy]

  # users
  resources :users, only: %i[new create update]
  resources :profile_images, only: %i[update destroy]
  resources :user_activations, only: %i[new edit]
  resources :password_resets, only: %i[new create edit update]
  get "/password_reset_success", to: "password_resets#mail_sent", as: "mail_sent"
  get "/profile", to: "profile#index", as: "profile"
  resources :sessions, only: %i[new create]
  resource :session, to: "sessions#destroy", only: %i[destroy], defaults: { id: nil }

  # carts and orders
  resource :cart, only: %i[show update]
  resources :orders, only: %i[new create]
  get "/orders/:uuid", to: "orders#show", as: "order_by_uuid"

  # admin pages
  namespace "admin" do
    get "/", to: "home#index"
    resources :products
    resources :product_categories
    resources :carts, only: %i[index show destroy]
    resources :orders, only: %i[index show destroy]
    resources :users, only: %i[index show edit update destroy] do
      resources :orders, only: %i[index]
    end
  end

  match "*unmatched", to: "application#render_404", via: :all
end

app/views/shared/_activate_user.html.erb
<% unless user.activated? %>
  <div class="container mb-3 p-2 border bg-light bg-gradient">
    Please, activate your account! Click this button to send activation link to your email.
    <%= link_to "Send activation link", new_user_activation_path, class: "btn btn-outline-info" %>
  </div>
<% end %>

app/views/shared/_add_to_cart_button.html.erb
<% if current_cart.has_item?(product.id) %>
  <div class="d-flex justify-content-center">
    <%= button_to cart_path(product_id: product.id, quantity: 0), method: :patch, class: "btn btn-outline-danger mr-1" do %>
      <i class="fa-solid fa-xmark"></i>
    <% end %>
    <%= link_to cart_path, class: "btn btn-outline-success" do %>
      <i class="fa-solid fa-cart-shopping"></i>
    <% end %>
  </div>
<% else %>
  <%= button_to cart_path(product_id: product.id, quantity: 1), method: :patch, class: "btn btn-outline-success" do %>
    <i class="fa-solid fa-cart-plus"></i>
  <% end %>
<% end %>

app/views/shared/_admin_button.html.erb
<% if current_user&.admin? %>
  <%= link_to "Admin", admin_path, class: 'btn btn-outline-info' %>
<% end %>

app/views/shared/_cart.html.erb
<%= link_to cart_path, class: 'btn btn-outline-success mr-1' do %>
  <%= cart.items&.count %><i class="fa-solid fa-cart-shopping ml-1"></i>
<% end %>

app/views/shared/_category.html.erb
<li>
  <%= link_to category.name, catalog_path(category_slug: category.slug) %>
  <% if category.has_children? %>
    <ul>
      <%= render_categories(category.children) %>
    </ul>
  <% end %>
</li>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> text-center">
    <% case key %>
    <% when "warning" %>
      <i class="fa-solid fa-triangle-exclamation"></i>
    <% when "info" %>
      <i class="fa-solid fa-info"></i>
    <% when "success" %>
      <i class="fa-regular fa-circle-check"></i>
    <% end %>
    <%= value %>
  </div>
<% end %>

app/views/shared/_items_table.html.erb
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total price</th>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %>
      <tr>
        <td><%= link_to item.product.name, item.product %></td>
        <td><%= item.product.price %></td>
        <td><%= item.quantity %></td>
        <td><%= item.product.price * item.quantity %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr class="table-dark text-dark">
      <td colspan="2"></td>
      <td>Total amount:</td>
      <td><%= total_amount %></td>
    </tr>
  </tfoot>
</table>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to "Store", root_path, class: 'navbar-brand'%>
    <%= render partial: "shared/admin_button" %>
    <div class="navbar-nav btn-group ml-auto">
      <%= render partial: "shared/cart", locals: { cart: current_cart } %>
      <%= render partial: "shared/profile_navbar", locals: { user: current_user } %>
    </div>
  </div>
</nav>
<div class='mb-2'></div>

app/views/shared/_navbar_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container text-white">
    <%= link_to "Store", root_path, class: 'navbar-brand' %>
    <%= render partial: "shared/admin_button" %>
    <div class="navbar-nav ml-auto">
      <%= render partial: "shared/profile_navbar", locals: { user: current_user } %>
    </div>
  </div>
</nav>
<div class='mb-2'></div>

app/views/shared/_order.html.erb
<div class="card border rounded-lg mb-3">
  <div class="card-header d-flex align-items-center">
    Order number: <%= order.id %>
    <%= link_to order_by_uuid_path(order.uuid), class: "btn btn-info mt-1 ml-auto" do %>
      <i class="fa-solid fa-circle-info"></i>
    <% end %>
  </div>
  <div class="card-body p-0">
    <% order.items.each do |item| %>
      <%= render partial: "shared/order_product", locals: { item: item } %>
    <% end %>
  </div>
  <div class="card-footer d-flex justify-content-between align-items-center">
    <span> <i class="fa-solid fa-calendar-days mr-2"></i> <%= order.created_at %> </span>
    <span> Total: <%= order.total_amount %> </span>
  </div>
</div>

app/views/shared/_order_product.html.erb
<div class="card rounded-0 border-0">
  <div class="card-body row d-flex align-items-center border-bottom mx-4 py-1">
    <div class="col-md-8">
      <%= link_to item.product.name, item.product %>
    </div>
    <div class="col">
      <%= item.quantity %>
    </div>
    <div class="col">
      <%= item.price_at_purchase %>
    </div>
    <div class="col">
      <%= item.total_amount %>
    </div>
    <hr>
  </div>
</div>

app/views/shared/_product_picture.html.erb
<% if url.present? %>
  <%= image_tag url, class: "img-fluid", alt: "Product image" %>
<% else %>
  <%= image_tag 'products/default.png', class: "img-fluid rounded-circle w-50", alt: "Product default image" %>
<% end %>

app/views/shared/_profile_navbar.html.erb
<div class="btn-group align-items-center justify-content-center text-white">
  <% if user.present? %>
    <%= link_to profile_path, class: "btn btn-outline-success" do %>
      <i class="fa-solid fa-user"></i>
    <% end %>
    <%= button_to session_path, method: :delete,
        form_class: "d-inline btn-group ml-1", class: "btn btn-outline-danger" do %>
          <i class="fa-solid fa-arrow-right-from-bracket"></i>
    <% end %>
  <% else %>
    <%= link_to "Sign In", new_session_path, class: "nav-item nav-link" %>
  <% end %>
</div>

app/views/shared/_user_profile_picture.html.erb
<div class="container w-25">
  <% if url.present? %>
    <%= image_tag url, class: "img-200 rounded-circle", alt: "User profile image" %>
  <% else %>
    <%= image_tag 'users/default.png', class: "img-200 rounded-circle", alt: "User profile default image" %>
  <% end %>
</div>