config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # catalog
  root to: "catalog#index"
  get "/catalog(/:category_slug)", to: "catalog#index", as: "catalog"
  resources :products, only: %i[show]
  resources :product_images, only: %i[destroy]

  # users
  resources :users, only: %i[new create update]
  resources :profile_images, only: %i[update destroy]
  resources :user_activations, only: %i[new edit]
  resources :password_resets, only: %i[new create edit update]
  get "/password_reset_success", to: "password_resets#mail_sent", as: "mail_sent"
  get "/profile", to: "profile#index", as: "profile"
  resources :sessions, only: %i[new create]
  resource :session, to: "sessions#destroy", only: %i[destroy], defaults: { id: nil }

  # carts and orders
  resource :cart, only: %i[show update]
  resources :orders, only: %i[new create]
  get "/orders/:uuid", to: "orders#show", as: "order_by_uuid"

  # admin pages
  namespace "admin" do
    get "/", to: "home#index"
    resources :products
    resources :product_categories
    resources :carts, only: %i[index show destroy]
    resources :orders, only: %i[index show destroy]
    resources :users, only: %i[index show edit update destroy] do
      resources :orders, only: %i[index]
    end
  end

  match "*unmatched", to: "application#render_404", via: :all
end

app/models/product.rb
class Product < ApplicationRecord
  include ImageUrl

  belongs_to :product_category
  has_many :cart_products, dependent: :destroy
  has_many :order_products
  has_one_attached :image

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :product_category_id, presence: true

  scope :published, -> { where("published_at <= ?", Time.zone.now) }
  scope :where_name_is_like, ->(name) { where("name ILIKE ?", "%#{name}%") if name.present? }
  scope :min_price_gte, ->(min_price) { where("price >= ?", min_price) if min_price.present? }
  scope :max_price_lte, ->(max_price) { where("price <= ?", max_price) if max_price.present? }

  def published?
    published_at.present? && published_at <= Time.zone.now
  end

  def category
    product_category.slug if product_category
  end

  def self.in_category(category_slug)
    category = ProductCategory.find_by_slug(category_slug)
    where(product_category: category.subtree)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_root_categories, only: %i[show new edit]

  def index
    @title = "Admin - Products"
    @products = Product.all
  end

  def show
    @title = "Admin - Product:#{params[:id]}"
  end

  def new
    @title = "Admin - New Product"
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:success] = "Product was successfully created."
      redirect_to admin_products_path
    else
      flash.now[:warning] = "Product wasn't created!"
      render :new
    end
  end

  def edit
    @title = "Admin - Product:#{params[:id]}"
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product was successfully updated."
      redirect_to admin_product_path(@product)
    else
      flash.now[:warning] = "Product wasn't updated!"
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Product was successfully deleted."
    redirect_to admin_products_path
  end

  def remove_product_image
    product = Product.find(params[:product_id])
    product.image.purge
    redirect_back fallback_location: request.referrer
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :price,
      :quantity,
      :image,
      :description,
      :product_category_id,
      :published_at,
      :image
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_root_categories
    @root_categories = ProductCategory.roots
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/views/admin/products/_form.html.erb
<div class="container">
  <%= form_for [:admin, product], html: { class: "form-horizontal", multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :price, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :quantity, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :quantity, class: "form-control", step: "1" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10">
        <%= f.label :image, class: "col-sm-2 control-label" %>
        <div>
          <%= f.file_field :image, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-2">
        <%= render partial: "shared/product_picture", locals: { url: product.image_url } %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :product_category_id, "Product Category", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select :product_category_id, nested_categories(@root_categories), :id, :name, { prompt: "Select category" }, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :published_at, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.datetime_field :published_at, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>  

app/views/admin/products/edit.html.erb
<div class="container">
  <h1>Edit Product</h1>
  <hr>
  <%= render partial: "form", locals: { product: @product, root_categories: @root_categories } %>
  <% if @product.image.attached? %>
    <%= button_to "Remove Image", product_image_path(@product), method: :delete, class: "btn btn-danger" %>
  <% end %>
  <%= button_to "Delete", admin_product_path(@product), method: :delete, data: { confirm: "Are you sure you want to delete this product?" }, class: "btn btn-danger" %>
</div>

app/views/admin/products/index.html.erb
<h1>Products</h1>
<%= link_to "New Product", new_admin_product_path, class: "btn btn-primary" %>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Category</th>
      <th scope="col">Published at</th>
      <th scope="col">Commands</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |p| %>
      <tr>
        <th scope="row"><%= p.id %></th>
        <td><%= p.name %></td>
        <td><%= p.price %></td>
        <td><%= p.quantity %></td>
        <td><%= p.category %></td>
        <td><%= p.published_at %></td>
        <td>
          <%= link_to "View", admin_product_path(p), class: "btn btn-info"%>
          <%= link_to "Edit", edit_admin_product_path(p), class: "btn btn-secondary" %> 
          <%= button_to "Delete", admin_product_path(p), method: :delete, 
              data: { confirm: "Are you sure you want to delete this product?" }, 
              form_class: "d-inline", class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<div class="container">
  <h1>New Product</h1>
  <hr>
  <%= render partial: "form", locals: { product: @product, root_categories: @root_categories } %>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <h1>Product: <%= @product.id %></h1>
  <hr>
  <%= render partial: "form", locals: { product: @product, root_categories: @root_categories } %>
  <% if @product.image.attached? %>
    <%= button_to "Remove Image", product_image_path(@product), method: :delete, class: "btn btn-danger" %>
  <% end %>
  <%= button_to "Delete", admin_product_path(@product), method: :delete, data: { confirm: "Are you sure you want to delete this product?" }, class: "btn btn-danger" %>
</div>