config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # catalog
  root to: "catalog#index"
  get "/catalog(/:category_slug)", to: "catalog#index", as: "catalog"
  resources :products, only: %i[show]
  resources :product_images, only: %i[destroy]

  # users
  resources :users, only: %i[new create update]
  resources :profile_images, only: %i[update destroy]
  resources :user_activations, only: %i[new edit]
  resources :password_resets, only: %i[new create edit update]
  get "/password_reset_success", to: "password_resets#mail_sent", as: "mail_sent"
  get "/profile", to: "profile#index", as: "profile"
  resources :sessions, only: %i[new create]
  resource :session, to: "sessions#destroy", only: %i[destroy], defaults: { id: nil }

  # carts and orders
  resource :cart, only: %i[show update]
  resources :orders, only: %i[new create]
  get "/orders/:uuid", to: "orders#show", as: "order_by_uuid"

  # admin pages
  namespace "admin" do
    get "/", to: "home#index"
    resources :products
    resources :product_categories
    resources :carts, only: %i[index show destroy]
    resources :orders, only: %i[index show destroy]
    resources :users, only: %i[index show edit update destroy] do
      resources :orders, only: %i[index]
    end
  end

  match "*unmatched", to: "application#render_404", via: :all
end

app/models/user.rb
class User < ApplicationRecord
  include ImageUrl

  attr_accessor :activation_token, :reset_token
  has_many :orders
  has_one :cart, dependent: :destroy
  has_secure_password
  has_one_attached :image

  validates :email, presence: true, uniqueness: true

  before_create :create_activation_digest

  def admin?
    is_admin
  end

  def activated?
    activated
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def update_activation_digest
    self.activation_token = Token.new_token
    update_attribute(:activation_digest, Token.digest(self.activation_token))
  end

  def create_reset_password_digest
    self.reset_token = Token.new_token
    update_attribute(:reset_password_digest,  Token.digest(reset_token))
    update_attribute(:reset_password_sent_at, Time.zone.now)
  end

  def password_reset_expired?
    reset_password_sent_at < 2.hours.ago
  end

  def send_activation_email
    UsersMailer.user_activation(self).deliver_now
  end

  def send_password_reset_email
    UsersMailer.password_reset(self).deliver_now
  end

  private

  def create_activation_digest
    self.activation_token = Token.new_token
    self.activation_digest = Token.digest(self.activation_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, except: [ :index ]

  def index
    @title = "Admin - Users"
    @users = User.all
  end

  def show
    @title = "Admin - User:#{params[:id]}"
  end

  def edit
    @title = "Admin - User:#{params[:id]}"
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User was successfully updated."
      redirect_to admin_user_path(@user)
    else
      flash.now[:warning] = "User wasn't updated!"
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User was successfully deleted."
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :is_admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      @user.send_activation_email
      flash[:success] = "Account was successfully created!"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/admin/users/_form.html.erb
<div class="container">
  <%= form_for [:admin, user], html: { class: "form-horizontal" } do |f| %>
    <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :email, readonly: true, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="checkbox col-sm-10">
        <label>
          <%= f.check_box :is_admin, {}, "true", "false" %> Admin
        </label>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>  

app/views/admin/users/edit.html.erb
<div class="container">
  <h1>Edit User</h1>
  <%= render partial: "shared/user_profile_picture", locals: { url: @user.image_url } %>
  <% if @user.image.attached? %>
    <%= button_to "Remove Image", profile_image_path(@user), method: :delete, class: "btn btn-danger" %>
  <% end %>
  <hr>
  <%= render partial: "form", locals: { user: @user } %>
  <%= button_to "Delete", admin_user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: "btn btn-danger" %>
</div>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Admin</th>
      <th scope="col">Created at</th>
      <th scope="col">Updated at</th>
      <th scope="col">Commands</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <th scope="row"><%= u.id %></th>
        <td><%= u.email %></td>
        <td><%= u.admin? ? "Yes" : "No" %></td>
        <td><%= u.created_at %></td>
        <td><%= u.updated_at %></td>
        <td>
          <%= link_to "View", admin_user_path(u), class: "btn btn-info"%>
          <%= link_to "Edit", edit_admin_user_path(u), class: "btn btn-secondary" %> 
          <%= button_to "Delete", admin_user_path(u), method: :delete, 
              data: { confirm: "Are you sure you want to delete this user?" }, 
              form_class: "d-inline", class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<div class="container">
  <h1>User: <%= @user.id %></h1>
  <%= render partial: "shared/user_profile_picture", locals: { url: @user.image_url } %>
  <% if @user.image.attached? %>
    <%= button_to "Remove Image", profile_image_path(@user), method: :delete, class: "btn btn-danger" %>
  <% end %>  <hr>
  <%= render partial: "form", locals: { user: @user } %>
  <hr>
  <% if @user.cart&.items&.any? %>
    User cart <%= link_to "View", admin_cart_path(@user.cart), class: "btn btn-info ml-1" %>
    <hr>
  <% end %>
  <% if @user.orders.any? %>
    This user has orders: <%= @user.orders.count %> <%= link_to "View", admin_user_orders_path(@user), class: "btn btn-info ml-1" %>
    <hr>
  <% end %>
  <%= button_to "Delete", admin_user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" }, class: "btn btn-danger" %>
</div>